"""add sync_records table

Revision ID: a4c693095e04
Revises: d07beafc6487
Create Date: 2026-03-08 20:15:44.245390
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a4c693095e04'
down_revision = 'd07beafc6487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('client_modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.String(length=1), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_client_id', 'sync_records', ['user_id', 'entity_type', 'client_id'], unique=False)
    op.create_index('idx_sync_entity', 'sync_records', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_sync_user_time', 'sync_records', ['user_id', 'server_modified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sync_user_time', table_name='sync_records')
    op.drop_index('idx_sync_entity', table_name='sync_records')
    op.drop_index('idx_sync_client_id', table_name='sync_records')
    op.drop_table('sync_records')
    # ### end Alembic commands ###
