"""add type and priority to events

Revision ID: b5d8e9c7f1a3
Revises: a4c693095e04
Create Date: 2026-03-10 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5d8e9c7f1a3'
down_revision = 'a4c693095e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 type 字段，默认 WORK
    op.add_column('events', sa.Column('type', sa.String(length=20), server_default='WORK', nullable=False))
    # 添加 priority 字段，默认 2（中等优先级）
    op.add_column('events', sa.Column('priority', sa.Integer(), server_default='2', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'priority')
    op.drop_column('events', 'type')
    # ### end Alembic commands ###
