"""add agent conversations table

Revision ID: c8e2f1a5b9d0
Revises: b5d8e9c7f1a3
Create Date: 2026-03-13 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c8e2f1a5b9d0'
down_revision = 'b5d8e9c7f1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建 agent_conversations 表
    op.create_table(
        'agent_conversations',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # 创建索引
    op.create_index('ix_agent_conversations_user_id', 'agent_conversations', ['user_id'])
    op.create_index('ix_agent_conversations_created_at', 'agent_conversations', ['created_at'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_conversations_created_at', table_name='agent_conversations')
    op.drop_index('ix_agent_conversations_user_id', table_name='agent_conversations')
    op.drop_table('agent_conversations')
    # ### end Alembic commands ###
